repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: mixed-line-ending
        args: ["-f", "lf"]
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: '24.8.0'
    hooks:
    -   id: black
        args:
            - "-S"
            - "-l"
            - "120"
        exclude: ^(ahk/_sync/.*\.py)
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
